version: '3'


services:

  http:
    dns:
    - 8.8.8.8
    - 9.9.9.9
    volumes:
    - .:/srv/app
    environment:
      MIX_ENV: dev
    build:
      args:
        MIX_ENV: dev
      context: '.'
      dockerfile: Dockerfile
    ports:
    - "8000:4000"
    command: sh -c "mix deps.get && mix ecto.setup && mix phx.server"
